### ISSUE TITLE
Using transform to encrypt data

### ISSUE THREAD

**Issue by th31nitiate** [choptastic/erlang_ds#2]
Hey,

I was looking at this and as it included in nitrogen by default it's useful. also I must use jt in some instances.

I wanted to ask if by any chance you have any recommendations on the encryption function or methodology. The erlang crypto library seems pretty good in general.

Any tips on the symmetric encryption method for fields in a record. 

- I guess using the users password as the key is the way to go right? Then decrypt it when the user logs in.
- what happens when when the user changes password, I guess decrypt and re encrypt?

The basic question here being how you may have used this or what conceptually you would imagine to be the best method.

I don't know any other utilises or methodologies at the moment.

**Comment by choptastic** [comment]
Happy new year, @th31nitiate!

I'm not familiar with "jt" (not sure if that was a typo, but I couldn't find anything on it).

I haven't specifically used `erlang_ds` for with encryption yet, but if the goal is to encrypt the data in an object before sending to a database, I imagine using some variation you've described would be a good way to do it.

(bear in mind, I'm no cryptographer, this just feels like a rough good practice)

I'd think that rather than using the user's password directly as the key, however, I would do the following:
1) Generate a salt and store the salt in that user record in the database
2) Generate a hash of the user's password with the generated salt.
3) Load the hash into a session variable
4) Use that hash to encrypt and decrypt sensitive data into and out of the database.

Once you have that you, could define a custom encryption module like this:

```erlang
-module(mycrypt).
-export([en/1, de/1]).

en(Term) ->
   Key = session(db_encryption_key),
   Data = term_to_binary(Term),
   _CipherText = encrypt_data(Key, Data).

de(CipherText) ->
   Key = session(db_encryption_key),
   Data = decrypt_data(Key, CipherText),
   _Term = binary_to_term(Data, [safe]).

..define decrypt_data/2 and encrypt_data/2 here...
presumably using crypto:crypto_one_time/5 with aes_256_cbc
```

Then you can register encryption/decryption updaters with `ds`:

```erlang
ds:register_updater(encrypt, {mycrypt, en, 1}),
ds:register_updater(decrypt, {mycrypt, de, 1}).
```

That will allow you to do:

```erlang
ds:transform(Obj, [
   {encrypt, [field1, field2, field3]}
]).
```

or to define it in the `app.config` with:

```erlang
[
...
  {erlang_ds, [
     {updaters, [
        {encrypt, {mycrypt, en, 1}},
        {decrypt, {mycrypt, de, 1}}
     ]}
  ]}
...
].
```

If I were doing something like you described, that's probably the pattern I'd use.

**Comment by th31nitiate** [comment]
Ok, cool this look is definitely what I'm hoping for. Using the hash seem better & my only fear is that I have access to the hash. If I new one time passwords then that would of been good.

If I use the users password as a key I can set it once & forget it. When I auth them is the only time I have access to it to decrypt the data.

I need to look into salts a little bit more. I think there could be a solution there. 

It's possible to have an application-wide encryption & decryption key shared amongst all users. The audit access to the key. Though that reduces security regarding who's got the possibility to access what. still puts the responsibility

The crypto lib is perfect. I'm not a cryptogher not good at it but it makes it accessible. 

Having them in the app config is much better than putting it in the init function.

**Comment by th31nitiate** [comment]
Happy New Year. Hope you have a good one. 

Typo I meant ds. I appreciate this it is great for many different concepts.

Ok, cool this is definitely what I'm hoping for. Using the hash seems better & my only fear is that I have access to the hash. If I knew one-time passwords then that would have been good.

If I use the user's password as a key I can set it once & forget it. When I auth them is the only time I have access to it, to decrypt the data.

I need to look into salts a little bit more. I think there could be a solution there. 

It's possible to have an application-wide encryption & decryption key shared amongst all users. The audit access to the key. However, that reduces security regarding who's got the possibility to access what. To be honest though that ent a specified responsibility. 

The crypto lib is perfect. I'm not a cryptographer nor good at it but it makes it accessible. 

Having them in the functions defined in app config is much better than putting it in the init function.

**Comment by choptastic** [comment]
Excellent!

Yeah, it depends on how secure you want it to be.

If the user's password changes, that would be one thing that might be a challenge, and in that case, you would indeed have to decrypt and re-encrypt the data with the new password.

That said, that would make a "forgot your password" function (where the system generates a new password for a user) effectively impossible, because without the original password, you would be unable to decrypt the existing data - maybe that's acceptable, but I suspect not.

In *that* case, the solution might very well be to store the each user's encryption key in the database (scary - if the database itself is leaked, the key is right there to decrypt data) or by storing the the key in another system or service that itself does some sort of challenge to request the data (that way, at least, if the main database is leaked somehow, the encryption key is still not available unless they managed to compromise the key server as well).

**Comment by th31nitiate** [comment]
Yes. This is logically sound in my view. That is the same as you described earlier using a salt then storing the hash. This would be a great way to solve this issue for a system without using an alternate service to store the data.

I came across the `aws-beam` library which is what I use to try create an authentication & authorization handler for nitrogen. I can store the encryption key somewhere there. Then cross reference access with with other logging information from the app. Then later set an alert to trigger if for example the encryption key is accessed and there is no log from the app that correlates to the login event.

I think the requirements are not that strict anyway so it's fine. Just basic auditibility is good. For other super strict apps it's just if you loose the key/password then you loose your data lol.

**Comment by choptastic** [comment]
Excellent!

Yeah, if a single encryption key is acceptable for the entire database, that certainly simplifies it (and allows using an external "secrets" tool, like you described from AWS).

I'm also very likely going to be adding a new secrets handler to Nitrogen as well, with a default one that just reads a config file from the home directory or something (e.g.: `$HOME/.nitrogen/appname.config`). Then it can just be calls to `wf:secret(Key)` to retrieve that secret.

With a handler, you could plug any secrets management system into it, like [AWS Key Management Service](https://docs.aws.amazon.com/kms/latest/developerguide/overview.html), [Blackbox](https://github.com/StackExchange/blackbox), [Red October](https://github.com/cloudflare/redoctober) or some other home-grown solution.

**Comment by th31nitiate** [comment]
Yes, that sounds super neat and all good solutions. Since the thing I'm working has no meaningful data of any kind I'm using mnesia (were ds is most useful) and then backing up to PostgreSQL. When it has around 500 MB to 1GB I can safely migrate to Postgresql. 

There is the issue of considering speed with encryption and decryption but as I'm only encrypting fields it doesn't matter much. Even with aes258, it should be an issue. Though 128 should be good enough. That is if Intel has not thought of circuitry to make these calculations computationally inexpensive.

Yes, I came across the Trello board for nitrogen it seems interesting will deffo be taking another look at some pointt. If I find time might pick up a card or two. Though I'm still learning around and have one or two ideas I would like to implement in it, maybe in the form of plugins or elements. I just have to grasp my way around it. I managed to do javascript api callbacks to Nitrogen the other day which was helpful with working incomplete workaround for the file upload appearance issue. 

Anyway, I'll go ahead and close this. Thanks for the insights it was very helpful.
